# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-04 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='spiritual_name',
        ),
    ]
