# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_remove_userprofile_spiritual_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('second_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('residential', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('is_employee', models.BooleanField(default=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
                ('office_email', models.CharField(blank=True, max_length=50, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeReference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=30)),
                ('organisation', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='intranet.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidentFundBeneficiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('residential', models.TextField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='intranet.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
        migrations.DeleteModel(
            name='AssetCategory',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='category',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='event',
        ),
        migrations.RemoveField(
            model_name='business',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='business',
            name='member',
        ),
        migrations.RemoveField(
            model_name='business',
            name='no_employee_estimate',
        ),
        migrations.RemoveField(
            model_name='business',
            name='type',
        ),
        migrations.RemoveField(
            model_name='businesstype',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='member',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='dues',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='dues',
            name='member',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='member',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ministry',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='member',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='member',
        ),
        migrations.RemoveField(
            model_name='testament',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='testament',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='tithe',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tithe',
            name='member',
        ),
        migrations.RemoveField(
            model_name='useracademicinfo',
            name='education',
        ),
        migrations.RemoveField(
            model_name='useracademicinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useremploymentinfo',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='useremploymentinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfamilyinfo',
            name='relations',
        ),
        migrations.RemoveField(
            model_name='userfamilyinfo',
            name='user',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='house',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='region',
            new_name='religion',
        ),
        migrations.RemoveField(
            model_name='department',
            name='coordinators',
        ),
        migrations.RemoveField(
            model_name='department',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='department',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='department',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='expected_completion_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='level',
        ),
        migrations.RemoveField(
            model_name='education',
            name='present',
        ),
        migrations.RemoveField(
            model_name='education',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='education',
            name='school_location',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='emergency_contact_email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='second_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='photograph',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='intranet.UserProfile'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='second_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceCategory',
        ),
        migrations.DeleteModel(
            name='AttendanceEvent',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='BusinessCoverage',
        ),
        migrations.DeleteModel(
            name='BusinessEmployeeEstimate',
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
        migrations.DeleteModel(
            name='Commitment',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Dues',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='EquipmentClass',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Ministry',
        ),
        migrations.DeleteModel(
            name='Offering',
        ),
        migrations.DeleteModel(
            name='Pledge',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Testament',
        ),
        migrations.DeleteModel(
            name='Tithe',
        ),
        migrations.DeleteModel(
            name='UserAcademicInfo',
        ),
        migrations.DeleteModel(
            name='UserEmploymentInfo',
        ),
        migrations.DeleteModel(
            name='UserFamilyInfo',
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intranet.UserProfile'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.Employee'),
        ),
        migrations.AddField(
            model_name='dependent',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='intranet.Employee'),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.Employee'),
        ),
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='intranet.Employee'),
        ),
    ]
