# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-26 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_auto_20181022_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceCertification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('return_date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('description_of_symptoms', models.TextField(blank=True, null=True)),
                ('doctor_consulted', models.BooleanField(default=False)),
                ('date_consulted', models.DateField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('name_of_doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('address_of_doctor', models.TextField(blank=True, null=True)),
                ('declaration', models.BooleanField(default=False)),
                ('employee_signed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('overview_of_absence', models.TextField(blank=True, null=True)),
                ('summary_of_interview', models.TextField(blank=True, null=True)),
                ('recommendations_and_actions', models.TextField(blank=True, null=True)),
                ('sick_pay_entitlement', models.FloatField(blank=True, null=True)),
                ('sick_pay_received', models.FloatField(blank=True, null=True)),
                ('payment_authorized', models.BooleanField(default=False)),
                ('manager_signed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_days_allowed', models.IntegerField()),
                ('no_of_days_taken', models.IntegerField()),
                ('no_of_days_left', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('account_number', models.CharField(max_length=30)),
                ('reliever', models.CharField(blank=True, max_length=100, null=True)),
                ('hand_over_notes', models.BooleanField(default=False)),
                ('hod_signed', models.BooleanField(default=False)),
                ('hr_signed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approval_reason', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.LeaveType'),
        ),
        migrations.AddField(
            model_name='absencecertification',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.LeaveType'),
        ),
    ]
