# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-29 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_auto_20181026_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='account_number',
        ),
    ]
