# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_auto_20181125_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencecertification',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absencecertification',
            name='no_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absencecertification',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absencecertification',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
