# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_auto_20181127_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photographs'),
        ),
    ]
